server:
  port: 8080
  servlet:
    context-path: /springboot

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/how2java

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
